In [3]:
import numpy as np

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(4,41,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [19]:
arr = [1,2,3,4,5]
padArr = np.pad(arr,(3,2),'constant', constant_values = (1,1))
padArr

array([1, 1, 1, 1, 2, 3, 4, 5, 1, 1])

In [20]:
arr = [1,2,3,4,5]
padArr = np.pad(arr, (2,2), 'maximum')
padArr

array([5, 5, 1, 2, 3, 4, 5, 5, 5])

In [21]:
arr = [1,2,3,4,5]
padArr = np.pad(arr, (2,2), 'minimum')
padArr

array([1, 1, 1, 2, 3, 4, 5, 1, 1])